title: Minh’s Terminal
description: Behavioral Data Science • UX • AI

remote_theme: b2a3e8/jekyll-theme-console

plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme

style: hacker

header_pages:
  - index.md
  - pages/about.md
  - pages/projects.md
  - pages/contact.md
custom_css:
  - assets/css/custom.css
